import type { ProviderMeta, ProviderId } from "./types";

export const PROVIDERS: Record<ProviderId, ProviderMeta> = {
  openai: {
    id: "openai",
    name: "OpenAI",
    color: "#10a37f",
    bgColor: "#10a37f1a",
    docsUrl: "https://platform.openai.com/docs/api-reference",
    statusUrl: "https://status.openai.com",
  },
  anthropic: {
    id: "anthropic",
    name: "Anthropic",
    color: "#c96442",
    bgColor: "#c964421a",
    docsUrl: "https://docs.anthropic.com",
    statusUrl: "https://status.anthropic.com",
  },
  google: {
    id: "google",
    name: "Google Gemini",
    color: "#4285f4",
    bgColor: "#4285f41a",
    docsUrl: "https://ai.google.dev/docs",
    statusUrl: "https://status.cloud.google.com",
  },
  cohere: {
    id: "cohere",
    name: "Cohere",
    color: "#d18ee2",
    bgColor: "#d18ee21a",
    docsUrl: "https://docs.cohere.com",
    statusUrl: "https://status.cohere.com",
  },
  huggingface: {
    id: "huggingface",
    name: "Hugging Face",
    color: "#ffd21e",
    bgColor: "#ffd21e1a",
    docsUrl: "https://huggingface.co/docs",
    statusUrl: "https://status.huggingface.co",
  },
  mistral: {
    id: "mistral",
    name: "Mistral AI",
    color: "#ff7000",
    bgColor: "#ff70001a",
    docsUrl: "https://docs.mistral.ai",
    statusUrl: "https://mistralai.statuspage.io",
  },
  groq: {
    id: "groq",
    name: "Groq",
    color: "#f55036",
    bgColor: "#f550361a",
    docsUrl: "https://console.groq.com/docs",
    statusUrl: "https://groqstatus.com",
  },
  together: {
    id: "together",
    name: "Together AI",
    color: "#0066ff",
    bgColor: "#0066ff1a",
    docsUrl: "https://docs.together.ai",
    statusUrl: "https://www.together.ai",
  },
  replicate: {
    id: "replicate",
    name: "Replicate",
    color: "#000000",
    bgColor: "#0000001a",
    docsUrl: "https://replicate.com/docs",
    statusUrl: "https://replicatestatus.com",
  },
  perplexity: {
    id: "perplexity",
    name: "Perplexity AI",
    color: "#20808d",
    bgColor: "#20808d1a",
    docsUrl: "https://docs.perplexity.ai",
    statusUrl: "https://status.perplexity.ai",
  },
  unknown: {
    id: "unknown",
    name: "Unknown",
    color: "#6b7280",
    bgColor: "#6b72801a",
    docsUrl: "",
    statusUrl: "",
  },
};

export const PROVIDER_LIST = Object.values(PROVIDERS).filter((p) => p.id !== "unknown");
